name = "UncertaintyOptimization"
uuid = "39e91f5d-ae59-4074-98e9-c7ab900f6468"
version = "1.0.0-DEV"
authors = ["Michal Kobiela <michal@walls.com.pl> and contributors"]

[deps]
IOCapture = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
IOCapture = "1.0.0"
ModelingToolkit = "10.26.1"
YAML = "0.4.14"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
