name = "UncertaintyOptimization"
uuid = "39e91f5d-ae59-4074-98e9-c7ab900f6468"
version = "1.0.0-DEV"
authors = ["Michal Kobiela <michal@walls.com.pl> and contributors"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
IOCapture = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PairPlots = "43a3c2be-4208-490b-832a-a21dcd55d7da"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
CSV = "0.10"
CairoMakie = "0.15.6"
DataFrames = "1.8.1"
Distributions = "0.25.122"
IOCapture = "0.2, 1"
ModelingToolkit = "10"
OrdinaryDiffEq = "6.103.0"
PairPlots = "3.0.3"
PreallocationTools = "0.4.34"
Revise = "3.12.1"
SciMLBase = "2.124.0"
StatsPlots = "0.15"
SymbolicIndexingInterface = "0.3.46"
Symbolics = "6"
Tables = "1.12.1"
Turing = "0.41.0"
YAML = "0.4.14"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
