name = "UncertaintyOptimization"
uuid = "39e91f5d-ae59-4074-98e9-c7ab900f6468"
version = "1.0.0-DEV"
authors = ["Michal Kobiela <michal@walls.com.pl> and contributors"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
IOCapture = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
CSV = "0.10.15"
IOCapture = "1.0.0"
ModelingToolkit = "10.26.1"
SciMLBase = "2.124.0"
Symbolics = "6.57.0"
Tables = "1.12.1"
YAML = "0.4.14"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
